I was getting this error on 'import third_party.statsd':
    File "third_party/statsd/__init__.py", line 12, in <module>
      getattr(settings, 'STATSD_HOST', 'localhost')
    File "/home/csilvers/google_appengine/lib/django-0.96/django/conf/__init__.py", line 28, in __getattr__
      self._import_settings()
    File "/home/csilvers/google_appengine/lib/django-0.96/django/conf/__init__.py", line 53, in _import_settings
      raise EnvironmentError, "Environment variable %s is undefined." % ENVIRONMENT_VARIABLE
  EnvironmentError: Environment variable DJANGO_SETTINGS_MODULE is undefined.

I have no idea what's causing this, but we don't care about django, so
I just added this exception as one that causes us to ignore django.

Auditors: chris

Test Plan:
   % python
   >>> import third_party.statsd
now succeeds without error.